import type { Player, GamemodeInfo } from "@/types"

export const GAMEMODES: GamemodeInfo[] = [
  { key: "overall", label: "Overall" },
  { key: "vanilla", label: "Vanilla" },
  { key: "uhc", label: "UHC" },
  { key: "pot", label: "Pot" },
  { key: "nethop", label: "NethOP" },
  { key: "smp", label: "SMP" },
  { key: "sword", label: "Sword" },
  { key: "axe", label: "Axe" },
  { key: "mace", label: "Mace" },
  { key: "ltm", label: "LTMs" },
]

export const players: Player[] = [
  {
    id: "1",
    name: "Aim4Flicker",
    uuid: "aim4flicker",
    region: "EU",
    avatar: "https://render.crafty.gg/3d/bust/Aim4Flicker",
    overall: 1,
    points: 9850,
    gamemodes: [
      { gamemode: "vanilla", tier: "HT1" },
      { gamemode: "nethop", tier: "HT1" },
      { gamemode: "sword", tier: "HT1" },
      { gamemode: "pot", tier: "HT2" },
      { gamemode: "uhc", tier: "MT2" },
      { gamemode: "smp", tier: "LT3" },
      { gamemode: "axe", tier: "HT2" },
      { gamemode: "mace", tier: "HT1" },
      { gamemode: "ltm", tier: "HT1" },
    ],
  },
  {
    id: "2",
    name: "Dream",
    uuid: "dream",
    region: "NA",
    avatar: "https://render.crafty.gg/3d/bust/Dream",
    overall: 2,
    points: 9200,
    gamemodes: [
      { gamemode: "vanilla", tier: "HT2" },
      { gamemode: "nethop", tier: "HT3" },
      { gamemode: "sword", tier: "HT2" },
      { gamemode: "pot", tier: "MT3" },
      { gamemode: "uhc", tier: "HT1" },
      { gamemode: "smp", tier: "HT1" },
      { gamemode: "axe", tier: "HT1" },
      { gamemode: "mace", tier: "MT2" },
      { gamemode: "ltm", tier: "HT2" },
    ],
  },
  {
    id: "3",
    name: "Technoblade",
    uuid: "technoblade",
    region: "NA",
    avatar: "https://render.crafty.gg/3d/bust/Technoblade",
    overall: 3,
    points: 8950,
    gamemodes: [
      { gamemode: "vanilla", tier: "HT2" },
      { gamemode: "nethop", tier: "MT3" },
      { gamemode: "sword", tier: "HT3" },
      { gamemode: "pot", tier: "HT2" },
      { gamemode: "uhc", tier: "HT3" },
      { gamemode: "smp", tier: "HT2" },
      { gamemode: "axe", tier: "HT3" },
      { gamemode: "mace", tier: "HT2" },
      { gamemode: "ltm", tier: "MT3" },
    ],
  },
  {
    id: "4",
    name: "Fruitberries",
    uuid: "fruitberries",
    region: "NA",
    avatar: "https://render.crafty.gg/3d/bust/Fruitberries",
    overall: 4,
    points: 8700,
    gamemodes: [
      { gamemode: "vanilla", tier: "HT4" },
      { gamemode: "nethop", tier: "HT2" },
      { gamemode: "sword", tier: "HT4" },
      { gamemode: "pot", tier: "HT3" },
      { gamemode: "uhc", tier: "HT4" },
      { gamemode: "smp", tier: "HT4" },
      { gamemode: "axe", tier: "HT4" },
      { gamemode: "mace", tier: "HT4" },
      { gamemode: "ltm", tier: "HT4" },
    ],
  },
  {
    id: "5",
    name: "Purpled",
    uuid: "purpled",
    region: "NA",
    avatar: "https://render.crafty.gg/3d/bust/Purpled",
    overall: 5,
    points: 8400,
    gamemodes: [
      { gamemode: "vanilla", tier: "MT5" },
      { gamemode: "nethop", tier: "HT4" },
      { gamemode: "sword", tier: "MT5" },
      { gamemode: "pot", tier: "HT4" },
      { gamemode: "uhc", tier: "MT5" },
      { gamemode: "smp", tier: "MT5" },
      { gamemode: "axe", tier: "MT5" },
      { gamemode: "mace", tier: "MT5" },
      { gamemode: "ltm", tier: "MT5" },
    ],
  },
  {
    id: "6",
    name: "Illumina",
    uuid: "illumina",
    region: "OCE",
    avatar: "https://render.crafty.gg/3d/bust/Illumina",
    overall: 6,
    points: 8100,
    gamemodes: [
      { gamemode: "vanilla", tier: "MT6" },
      { gamemode: "nethop", tier: "MT6" },
      { gamemode: "sword", tier: "MT6" },
      { gamemode: "pot", tier: "MT6" },
      { gamemode: "uhc", tier: "MT6" },
      { gamemode: "smp", tier: "MT6" },
      { gamemode: "axe", tier: "MT6" },
      { gamemode: "mace", tier: "MT6" },
      { gamemode: "ltm", tier: "MT6" },
    ],
  },
  {
    id: "7",
    name: "Clowmii",
    uuid: "clowmii",
    region: "EU",
    avatar: "https://render.crafty.gg/3d/bust/Clowmii",
    overall: 7,
    points: 7800,
    gamemodes: [
      { gamemode: "vanilla", tier: "MT7" },
      { gamemode: "nethop", tier: "MT7" },
      { gamemode: "sword", tier: "MT7" },
      { gamemode: "pot", tier: "MT7" },
      { gamemode: "uhc", tier: "MT7" },
      { gamemode: "smp", tier: "MT7" },
      { gamemode: "axe", tier: "MT7" },
      { gamemode: "mace", tier: "MT7" },
      { gamemode: "ltm", tier: "MT7" },
    ],
  },
  {
    id: "8",
    name: "TapL",
    uuid: "tapl",
    region: "NA",
    avatar: "https://render.crafty.gg/3d/bust/TapL",
    overall: 8,
    points: 7500,
    gamemodes: [
      { gamemode: "vanilla", tier: "MT8" },
      { gamemode: "nethop", tier: "MT8" },
      { gamemode: "sword", tier: "LT8" },
      { gamemode: "pot", tier: "MT8" },
      { gamemode: "uhc", tier: "MT8" },
      { gamemode: "smp", tier: "LT8" },
      { gamemode: "axe", tier: "MT8" },
      { gamemode: "mace", tier: "MT8" },
      { gamemode: "ltm", tier: "MT8" },
    ],
  },
  {
    id: "9",
    name: "PeteZahHutt",
    uuid: "petezahhutt",
    region: "NA",
    avatar: "https://render.crafty.gg/3d/bust/PeteZahHutt",
    overall: 9,
    points: 7200,
    gamemodes: [
      { gamemode: "vanilla", tier: "LT9" },
      { gamemode: "nethop", tier: "LT9" },
      { gamemode: "sword", tier: "LT9" },
      { gamemode: "pot", tier: "LT9" },
      { gamemode: "uhc", tier: "LT9" },
      { gamemode: "smp", tier: "LT9" },
      { gamemode: "axe", tier: "LT9" },
      { gamemode: "mace", tier: "LT9" },
      { gamemode: "ltm", tier: "LT9" },
    ],
  },
  {
    id: "10",
    name: "Bitzel",
    uuid: "bitzel",
    region: "EU",
    avatar: "https://render.crafty.gg/3d/bust/Bitzel",
    overall: 10,
    points: 6900,
    gamemodes: [
      { gamemode: "vanilla", tier: "LT10" },
      { gamemode: "nethop", tier: "LT10" },
      { gamemode: "sword", tier: "LT10" },
      { gamemode: "pot", tier: "LT10" },
      { gamemode: "uhc", tier: "LT10" },
      { gamemode: "smp", tier: "LT10" },
      { gamemode: "axe", tier: "LT10" },
      { gamemode: "mace", tier: "LT10" },
      { gamemode: "ltm", tier: "LT10" },
    ],
  },
]
